version: "3"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    depends_on:
      - db
    environment:
       SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqubedb
       SONAR_JDBC_USERNAME: sonar
       SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonar/opt/sonarqube/data:/opt/sonarqube/data
      - ./sonar/opt/sonarqube/extentions:/opt/sonarqube/extensions
      - ./sonar/opt/sonarqube/logs/:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    container_name: postgresql
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqubedb
    volumes:
      - ./postgresql/var/lib/postgresql:/var/lib/postgresql
      - ./postgresql/var/lib/postgresql/data:/var/lib/postgresql/data
