FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base

LABEL Description="WebTest"
LABEL version="1.0"
LABEL Author="caner.demirci"
# MAINTAINER caner.demirci #deprecated
# docker image inspect --format='' myimage

RUN mkdir /myvol && echo "hello world" > /myvol/greeting
VOLUME /myvol

WORKDIR /app
EXPOSE 7230

ENV ASPNETCORE_URLS=http://+:7230
ENV MY_NAME="Caner Demirci"

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY ["WebTest.csproj", "./"]
RUN dotnet restore "WebTest.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "WebTest.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebTest.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebTest.dll"]

# docker build -t webtest .
# docker run -d -p 7230:7230 webtest
# http://localhost:7230/
